### ISSUE TITLE
有道全文翻译报错

### ISSUE THREAD

**Issue by mrwangxc** [easeflyer/gd_plugin#8]
只要包含 / 字符，翻译都会报错。例如这段
This implementation is designed to allow the end user to move in a city to obtain additional content related to the surrounding environment (monuments, objects, etc.) by using smartphones and/or VR/AR/MR-like devices
报错内容：
查询错误：程序返回，退出代码为 255. [16126] Failed to execute script youdao_get Traceback (most recent call last): File "youdao_get.py", line 39, in <module> File "urllib/request.py", line 163, in urlopen File "urllib/request.py", line 472, in open File "urllib/request.py", line 582, in http_response File "urllib/request.py", line 510, in error File "urllib/request.py", line 444, in _call_chain File "urllib/request.py", line 590, in http_error_default urllib.error.HTTPError: HTTP Error 404: Not Found

是不是对 / 的处理还是有些问题？

**Comment by easeflyer** [comment]
感谢反馈！  抽时间，把这个问题解决了。;)
