### ISSUE TITLE
youdao_post.py 报错不能正常使用

### ISSUE THREAD

**Issue by JinQinBNU** [easeflyer/gd_plugin#9]
系统 ubuntu22.04

`./youdao_post.py "test"
`
python3.5

>Traceback (most recent call last):
  File "./youdao_post.py", line 79, in <module>
    for res in obj1['translateResult'][0]:
KeyError: 'translateResult'

python3.10报错

> Traceback (most recent call last):
  File "~/gd_plugin/youdao/./youdao_post.py", line 74, in <module>
    obj1 = json.loads(json1,encoding='utf-8')
  File "/usr/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: JSONDecoder.__init__() got an unexpected keyword argument 'encoding'

**Comment by easeflyer** [comment]
感谢反馈，经过实验，开放的 post 接口的翻译质量，貌似不如 get 接口，因此就没有再继续完善 post 接口。 youdao_get.py 也可以处理小段文字，方译质量相对较高。所以可以考虑使用 youdao_get.py。

**Comment by JinQinBNU** [comment]
> 感谢反馈，经过实验，开放的 post 接口的翻译质量，貌似不如 get 接口，因此就没有再继续完善 post 接口。 youdao_get.py 也可以处理小段文字，方译质量相对较高。所以可以考虑使用 youdao_get.py。

好的 感谢回复 现在跟google翻译一起用～
